FROM phusion/baseimage:0.9.17
MAINTAINER pitrho

ENV DEBIAN_FRONTEND noninteractive
ENV CASSANDRA_VERSION %%CASSANDRA_VERSION%%

# Install Oracle Java 8
RUN apt-add-repository ppa:webupd8team/java \
  && apt-get update \
  && echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections \
  && apt-get install -y oracle-java8-installer dnsutils

# Install cassandra
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 514A2AD631A57A16DD0047EC749D6EEC0353B12C
RUN echo 'deb http://www.apache.org/dist/cassandra/debian 22x main' >> /etc/apt/sources.list.d/cassandra.list

RUN apt-get update \
	&& apt-get install -y cassandra="$CASSANDRA_VERSION" \
	&& rm -rf /var/lib/apt/lists/*

ENV CASSANDRA_CONFIG /etc/cassandra

# listen to all rpc
RUN sed -ri ' \
		s/^(rpc_address:).*/\1 0.0.0.0/; \
	' "$CASSANDRA_CONFIG/cassandra.yaml"

# 7000: intra-node communication
# 7001: TLS intra-node communication
# 7199: JMX
# 9042: CQL
# 9160: thrift service
EXPOSE 7000 7001 7199 9042 9160

# Add all services files
RUN mkdir /etc/service/cassandra
COPY run.sh /etc/service/cassandra/run

# Add cqlshrc file
RUN mkdir /root/.cassandra
COPY cqlshrc /root/.cassandra/cqlshrc

CMD ["/sbin/my_init"]
